# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Build app and deploy to Github Pages
on:
  # 监听push操作
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    # 运行环境
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist # 3.打包后文件的输出目录(根据你自己的项目情况而定)
          github_token: ${{ secrets.DEPLOY_TOKEN }} # 4.刚才你C下来的仓库token秘钥!!!
          user_name: ${{ secrets.MY_USER_NAME }} # 不用改
          user_email: ${{ secrets.MY_USER_EMAIL }} # 不用改
          commit_message: 自动部署 # 5.部署时的 git 提交信息，自由填写
